### ISSUE TITLE
Failed to activate the syntax-theme-auto-changer package... got stuck

### ISSUE THREAD

**Issue by ghost** [nobuhito/syntax-theme-auto-changer#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [syntax-theme-auto-changer](https://github.com/nobuhito/syntax-theme-auto-changer) package 0.9.4

### Stack Trace

Failed to activate the syntax-theme-auto-changer package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.44.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:146745)
    at /packages/syntax-theme-auto-changer/lib/syntax-theme-auto-changer-view.coffee:1:10)
    at /packages/syntax-theme-auto-changer/lib/syntax-theme-auto-changer-view.coffee:1:1)
    at /packages/syntax-theme-auto-changer/lib/syntax-theme-auto-changer-view.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:146745)
    at /packages/syntax-theme-auto-changer/lib/syntax-theme-auto-changer.coffee:2:30)
    at /packages/syntax-theme-auto-changer/lib/syntax-theme-auto-changer.coffee:1:1)
    at /packages/syntax-theme-auto-changer/lib/syntax-theme-auto-changer.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:1:734076)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:3331586)
    at Package.activateNow (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:3319570)
    at measure (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:3319348)
    at Package.measure (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:3316958)
```

### Commands

```
```

### Non-Core Packages

```
amnesia-io 0.4.6 
atom-clock 0.1.17 
atom-language-Io 0.2.0 
atom-material-syntax undefined 
atom-material-ui undefined 
atom-npm 0.3.1 
atom-select-npm-install 1.0.2 
atom-sproto-syntax 0.1.0 
atom-xcode 0.1.3 
autocomplete-paths 2.12.2 
bootstrap-3-snippets-for-atom 2.19.0 
build-npm-apm 0.12.0 
busy-signal 2.0.1 
captain-hook 0.0.1 
command-syntax 0.1.4 
copy-with-syntax 0.0.3 
dataflex-syntax 0.3.0 
editorconfig 2.6.0 
emoji-syntax 1.7.6 
extract-web 0.3.2 
hey-pane 1.2.0 
howdoi 0.1.1 
Hydrogen 2.14.0 
iam-syntax 0.1.5 
intentions 1.1.5 
ionic 1.3.0 
ios 0.1.0 
jekyll-syntax-highlighting 0.1.0 
jshint 1.8.6 
K-Syntax 2.0.0 
language-ampl-syntax 1.2.0 
language-pegjs 0.5.0 
lay-out-syntax 1.3.0 
linter 2.3.1 
linter-perl-check-syntax 0.8.1 
linter-ui-default 1.8.1 
minimap-tree-sitter-syntax 0.0.0 
npm 2.0.0 
npm-license-checker 1.1.2 
pairing-chat 0.2.1 
pcc-syntax 0.4.0 
polymer-snippets 3.2.1 
preview-plus 1.2.7 
qcobjects-syntax 0.7.1 
r-syntax 1.0.5 
ruby-syntax-replacer 0.5.1 
schelp-syntax 0.6.3 
scheme-syntax 0.4.0 
scp-atom-syntax 0.1.1 
script 3.25.0 
scroll-through-time 0.3.1 
set-syntax 0.4.0 
set-syntax-emacs 0.1.0 
sync-settings 3.0.0 
syntax-highlighting-scopes-showroom 1.0.0 
syntax-neonize 3.3.0 
syntax-theme-auto-changer 0.9.4 
teletype 0.13.4 
tool-bar 1.2.0 
town-crier 0.3.0 
tree-sitter-syntax-visualizer 0.0.2 
turbo-syntax 0.4.3 
vash-syntax 0.3.0 
webdriverio-snippets 0.5.2 
zentabs 0.8.9 
```

**Comment by ghost** [comment]
Dont have clue what to do
